

server:
   port: 8761

eureka:
   instance:
       hostname: localhost
   client:
       registerWithEureka: false
       fetchRegistry: false
       serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


spring:
  application:
    name: eureka-server
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888
      discovery:
        enabled: true
        service-id: config-server
