server:
   port: 9200

eureka:
  client:
    instance:
      prefer-ip-address: true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://localhost:8761/eureka/



spring:
  application:
    name: zookeeper-client
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888
      discovery:
        enabled: true
        service-id: config-server
